backend:
  name: git-gateway
  branch: main  # ← Make sure this matches your GitHub default branch

publish_mode: editorial_workflow  # Enables draft + review system
media_folder: "static/uploads"  # Folder where uploaded files are stored
public_folder: "/uploads"       # Public-facing URL for media

site_url: "http://cia-site.org"

collections:
  # ----------- Anomalies / Entities -----------
  - name: "anomalies"
    label: "Anomalies"
    folder: "content/anomalies"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Anomaly ID", name: "id", widget: "string" }
      - { label: "Threat Level", name: "threat_level", widget: "select", options: ["Low", "Moderate", "High", "Extreme"] }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Containment Procedures", name: "containment", widget: "markdown" }
      - { label: "Discovery Log", name: "discovery", widget: "markdown" }
      - { label: "Images", name: "images", widget: "image", required: false }

  # ----------- Incident / Field Reports -----------
  - name: "reports"
    label: "Field Reports"
    folder: "content/reports"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Agent Name", name: "agent", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "markdown" }
      - { label: "Attachments", name: "attachments", widget: "image", required: false }

  # ----------- Containment Logs -----------
  - name: "containment"
    label: "Containment Logs"
    folder: "content/containment"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Object ID", name: "object_id", widget: "string" }
      - { label: "Containment Team", name: "team", widget: "string" }
      - { label: "Procedure Details", name: "procedure", widget: "markdown" }
      - { label: "Status", name: "status", widget: "select", options: ["Active", "Neutralized", "Ongoing"] }

  # ----------- Directives -----------
  - name: "directives"
    label: "Directives"
    folder: "content/directives"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Directive Title", name: "title", widget: "string" }
      - { label: "Issued By", name: "issued_by", widget: "string" }
      - { label: "Issued Date", name: "date", widget: "datetime" }
      - { label: "Directive Text", name: "body", widget: "markdown" }
