backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "directives"
    label: "Directives"
    folder: "content/directives"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "watchlogs"
    label: "Watchlogs"
    folder: "content/watchlogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Camera ID", name: "camera_id", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "containment_logs"
    label: "Containment Logs"
    folder: "content/containment"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Subject ID", name: "subject_id", widget: "string" }
      - { label: "Containment Level", name: "containment_level", widget: "select", options: ["Low", "Moderate", "High", "Critical"] }
      - { label: "Body", name: "body", widget: "markdown" }
